name: iControlU
main: icontrolu\iControlU
version: 1.5
author: Falkirks
api: [3.0.0-ALPHA12]
load: POSTWORLD
commands:
 icu:
  permission: icu.use
  description: Control other players
  usage: /icu <control <player> / stop>
permissions:
 icu:
  default: op
  children:
   icu.use:
    default: op
    description: Main iControlU perm
   icu.control:
    default: op
    description: Can control others
   icu.stop:
    default: op
    description: Stop controlling
   icu.exempt:
    default: op
    description: Exempt from being controlled
